version: "3.8"

services:
  app:
    build: .
    container_name: riva-cake-app
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: riva-cake-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbkidut   
      MYSQL_USER: kidut
      MYSQL_PASSWORD: naninuneno
    ports:
      - "3307:3306"   
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: riva-cake-phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
